### Create user
POST http://localhost:5000/api/users HTTP/1.1
content-type: application/json

{
    "userId": "kjhfdg8043nsSGke30aS",
    "name": "Laura Gonzalez",
    "age": "27",
    "weight": "10"
}

### Get user
GET http://localhost:5000/api/users/kjhfdg8043nsSGke30aS HTTP/1.1

### Get wrong user
GET http://localhost:5000/api/users/kjdfh45yh5jthtjhe30aS HTTP/1.1

### List users
GET http://localhost:5000/api/users HTTP/1.1

### Delete user
DELETE http://localhost:5000/api/users/kjhfdg8043nsSGke30aS HTTP/1.1

### Edit user
PUT http://localhost:5000/api/users/kjhfdg8043nsSGke30aS HTTP/1.1
content-type: application/json

{
    "name": "Laura Gonzalez",
    "age": "16",
    "weight": "20"
}